#!/bin/bash
#A script for using make_CRAB_configuration.py to write CRAB configuration files for datasets specified in dataset_input.txt.
#
#It is recommended to run this script in the Configurations folder of NTupleTools, so that the created CRAB configuration files go into the correct locations/folders.
#If it is run from another location, any new folder(s) will be created in the working location, into which the created files will be placed, that is all.
#
#With current filepaths (as committed), make_CRAB_configuration.py should be in the same folder as this make_CRAB_configuration_from_file.sh script
#and das_client.py should be in the ../tools folder relative to this script.
#
#Simply run with: ./make_ntuples_CRAB_configurations.sh >&makentuplesconfigs.log &

#Data (LeptonPlus3Jets skim)
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/ElectronHad/Run2011A-12Oct2013-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=600 --lumi_mask=Cert_190456-203742_8TeV_22Jan2013ReReco_Collisions12_JSON.txt --useData=1 --dataType=ElectronHad --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/ElectronHad/Run2011B-12Oct2013-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=2000 --lumi_mask=Cert_190456-203742_8TeV_22Jan2013ReReco_Collisions12_JSON.txt --useData=1 --dataType=ElectronHad --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/SingleMu/Run2011A-12Oct2013-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=500 --lumi_mask=Cert_190456-203742_8TeV_22Jan2013ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleMu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/SingleMu/Run2011B-12Oct2013-v1/AOD --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=0 --numberlumis=-1 --numberjobs=1500 --lumi_mask=Cert_190456-203742_8TeV_22Jan2013ReReco_Collisions12_JSON.txt --useData=1 --dataType=SingleMu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

#Monte Carlo (LeptonPlus3Jets skim)
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/TTJets_MSDecays_central_TuneZ2_7TeV-madgraph-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=TTJets --skim=LeptonPlus3Jets --storePDFWeights=1 --isTTbarMC=1 --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/T_TuneZ2_t-channel_7TeV-powheg-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=T_t-channel --skim=LeptonPlus3Jets --storePDFWeights=1 --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/Tbar_TuneZ2_t-channel_7TeV-powheg-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=Tbar_t-channel --skim=LeptonPlus3Jets --storePDFWeights=1 --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/T_TuneZ2_s-channel_7TeV-powheg-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=700 --lumi_mask=None --useData=0 --dataType=T_s-channel --skim=LeptonPlus3Jets --storePDFWeights=1 --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/Tbar_TuneZ2_s-channel_7TeV-powheg-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=350 --lumi_mask=None --useData=0 --dataType=Tbar_s-channel --skim=LeptonPlus3Jets --storePDFWeights=1 --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/T_TuneZ2_tW-channel-DR_7TeV-powheg-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=900 --lumi_mask=None --useData=0 --dataType=T_tW-channel --skim=LeptonPlus3Jets --storePDFWeights=1 --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/Tbar_TuneZ2_tW-channel-DR_7TeV-powheg-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=900 --lumi_mask=None --useData=0 --dataType=Tbar_tW-channel --skim=LeptonPlus3Jets --isTTbarMC=1 --isMCatNLO=1 --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-20to30_BCtoE_TuneZ2_7TeV-pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_20_30_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-30to80_BCtoE_TuneZ2_7TeV-pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_30_80_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-80to170_BCtoE_TuneZ2_7TeV-pythia/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_80_170_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-20to30_EMEnriched_TuneZ2_7TeV-pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_170_250_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-30to80_EMEnriched_TuneZ2_7TeV-pythia/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_250_350_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-80to170_EMEnriched_TuneZ2_7TeV-pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt_350_BCtoE --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-170to250_EMEnriched_TuneZ2_7TeV-pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_20_30_EMEnriched --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-250to350_EMEnriched_TuneZ2_7TeV-pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_30_80_EMEnriched --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-350_EMEnriched_TuneZ2_7TeV-pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1000 --lumi_mask=None --useData=0 --dataType=QCD_Pt_80_170_EMEnriched --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/GJets_TuneZ2_40_HT_100_7TeV-madgraph/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1400 --lumi_mask=None --useData=0 --dataType=GJets_HT-200To400 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/GJets_TuneZ2_100_HT_200_7TeV-madgraph/Summer11LegDR-PU_S13_START53_LV6-v3/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=GJets_HT-400ToInf --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-15to20_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=500 --lumi_mask=None --useData=0 --dataType=QCD_Pt_20_MuEnrichedPt_15 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-20to30_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=50 --lumi_mask=None --useData=0 --dataType=QCD_Pt-15to20_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-30to50_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=250 --lumi_mask=None --useData=0 --dataType=QCD_Pt-20to30_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-50to80_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=250 --lumi_mask=None --useData=0 --dataType=QCD_Pt-30to50_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-80to120_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=300 --lumi_mask=None --useData=0 --dataType=QCD_Pt-50to80_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-120to170_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=250 --lumi_mask=None --useData=0 --dataType=QCD_Pt-80to120_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-170to300_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=250 --lumi_mask=None --useData=0 --dataType=QCD_Pt-120to170_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-300to470_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=QCD_Pt-170to300_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-470to600_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=200 --lumi_mask=None --useData=0 --dataType=QCD_Pt-300to470_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-600to800_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=100 --lumi_mask=None --useData=0 --dataType=QCD_Pt-470to600_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-800to1000_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=100 --lumi_mask=None --useData=0 --dataType=QCD_Pt-600to800_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/QCD_Pt-1000_MuEnrichedPt5_TuneZ2_7TeV_pythia6/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=100 --lumi_mask=None --useData=0 --dataType=QCD_Pt-800to1000_MuEnrichedPt5 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/DYJetsToLL_TuneZ2_M-50_7TeV-madgraph-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=900 --lumi_mask=None --useData=0 --dataType=DYJetsToLL_M-50 --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/WJetsToLNu_TuneZ2_7TeV-madgraph-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=500 --lumi_mask=None --useData=0 --dataType=WJetsToLNu --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/W2Jets_TuneZ2_7TeV-madgraph-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=1500 --lumi_mask=None --useData=0 --dataType=W2Jets --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/W4Jets_TuneZ2_7TeV-madgraph-tauola/Summer11LegDR-PU_S13_START53_LV6-v1/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=400 --lumi_mask=None --useData=0 --dataType=W4Jets --skim=LeptonPlus3Jets --mail=None --whiteList=None --blackList=None

python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/TTJets_MSDecays_scaleup_TuneZ2star_7TeV-madgraph-tauola/Summer11LegDR-PU_S13_START53_LV6-v2/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=150 --lumi_mask=None --useData=0 --dataType=TTJets-scaleup --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None
python make_CRAB_configuration.py --jobtype=cmssw --scheduler=remoteGlidein --use_server=0 --version=v11 --datasetpath=/TTJets_MSDecays_scaledown_TuneZ2star_7TeV-madgraph-tauola/Summer11LegDR-PU_S13_START53_LV6-v2/AODSIM --pset=BristolAnalysis/NTupleTools/test/makeTuples_cfg.py --numberevents=-1 --numberlumis=0 --numberjobs=150 --lumi_mask=None --useData=0 --dataType=TTJets-scaledown --skim=LeptonPlus3Jets --isTTbarMC=1 --mail=None --whiteList=None --blackList=None